### ISSUE TITLE
LocallyConnected layer does not seem to be fully implemented

### ISSUE THREAD

**Issue by lolz0r** [facebook/fbnn#8]
Hello,
When I try to use fbnn:LocallyConnected the system crashes with the following error:

/torch/install/bin/luajit: ...0r/torch/install/share/lua/5.1/fbnn/LocallyConnected.lua:118: attempt to call field 'LocallyConnected_updateOutput' (a nil value)
stack traceback:
	...0r/torch/install/share/lua/5.1/fbnn/LocallyConnected.lua:118: in function 'updateOutput'
	/home/lolz0r/torch/install/share/lua/5.1/nn/Sequential.lua:39: in function 'forward'
	4_train.lua:161: in function 'opfunc'
	/home/lolz0r/torch/install/share/lua/5.1/optim/cg.lua:78: in function 'optimMethod'
	4_train.lua:211: in function 'train'
	doall.lua:80: in main chunk
	[C]: in function 'dofile'
	...lz0r/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670

LocallyConnected_updateOutput is nil? Any ideas?

**Comment by ajtulloch** [comment]
You probably need to require 'fbcunn' as well: https://github.com/facebook/fbcunn/blob/master/src/LocallyConnectedHost.cpp

**Comment by lolz0r** [comment]
@ajtulloch Thanks for the idea unfortunately including fbcunn does not seem to fix the issue. Do you know of any example out there that uses the locallyconnected layer? I was searching test code or anything else but nothing out there seems to actually use this layer... that I could find.

**Comment by lolz0r** [comment]
As an intresting investigation I rebuilt all of my fb related libs. I noticed that while rebuilding fbnn that it appears that not all files are being included in the build:

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/lolz0r/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1";
make
   
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/lolz0r/torch/install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lolz0r/fbnn/build
Scanning dependencies of target fbnn
[ 50%] Building C object CMakeFiles/fbnn.dir/init.c.o
Linking C shared module libfbnn.so
[ 50%] Built target fbnn
Scanning dependencies of target fbnn_static
[100%] Building C object CMakeFiles/fbnn_static.dir/init.c.o
Linking C static library libfbnn.a
[100%] Built target fbnn_static
cd build && make install
[ 50%] Built target fbnn
[100%] Built target fbnn_static
Install the project...
-- Install configuration: "Release"
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lib/libfbnn.so
-- Set runtime path of "/home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lib/libfbnn.so" to "$ORIGIN/../lib:/home/lolz0r/torch/install/lib"
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/SparseConverter.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/CachingLookupTable.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/Dropout.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/HSM.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/CrossMapNormalization.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/Optim.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/SparseKmax.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/init.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/GroupKMaxPooling.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/ClassNLLCriterionWithUNK.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/SparseLinear.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/Probe.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/SparseNLLCriterion.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/WeightedLookupTable.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/SequentialCriterion.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/ClassHierarchicalNLLCriterion.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/SparseSum.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/SparseThreshold.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/TrueNLLCriterion.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/ProjectiveGradientNormalization.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/LocallyConnected.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/SparseLookupTable.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/test.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/KMaxPooling.lua
-- Installing: /home/lolz0r/torch/install/lib/luarocks/rocks/fbnn/scm-1/lua/fbnn/LinearNB.lua
Updating manifest for /home/lolz0r/torch/install/lib/luarocks/rocks
fbnn scm-1 is now built and installed in /home/lolz0r/torch/install/ (license: BSD)

```
The thing to note is that it appears that only init.c is being compiled, not LocallyConnected.cpp ... or others. I will investigate the build script...

**Comment by lolz0r** [comment]
It looks like only init.c is included in the CMakeLists.txt - however adding the addional files leads to addional compile errors. 

So confused! :/

**Comment by soumith** [comment]
you did not call :cuda() on your layer, that's why this error. While we have released the CPU code for LocallyConnected layer, the building was not enabled because the CPU code needs Intel MKL as a hard dependency and not many people have it available to them.

**Comment by lolz0r** [comment]
Thanks for the pointer. I added a :cuda() to the initizialtion of the layer:

nn.LocallyConnected(3, width, height, 3, 3, 5, 5):cuda()

It now errors out with:
Module: must provide a type to convert to

I tried being explict:

nn.LocallyConnected(3, width, height, 3, 3, 5, 5):type('torch.CudaTensor')

still no luck... :/

I am super excited to experiment with this layer type but seem to be hung on a trivial issue. Please advise.

**Comment by lolz0r** [comment]
It errors from line:  /torch/install/share/lua/5.1/fbnn/LocallyConnected.lua:201: in function 'type'

Which looks like:
 if self:type() == 'torch.CudaTensor' and type ~= 'torch.CudaTensor' then

.. it is calling type with no arguments... which hits assert in Module.lua:
 assert(type, 'Module: must provide a type to convert to')

It seems like something is not being overriden correctly.

**Comment by soumith** [comment]
oh I think I know the issue. We have an internal override in Module.lua

Can you use the getParamsByDevice branch of nn:

git clone https://github.com/torch/nn && cd nn && git checkout getParamsByDevice && luarocks make rocks/nn-scm-1.rockspec

see if that works...

**Comment by lolz0r** [comment]
right on! That seems to fix the issue. 

I am now running out of cuda memory but that is likely just an issue of my model setup. Luckily I bought a 4GB card today... lets hope it is enough!

Thanks!

**Comment by soumith** [comment]
The local layers are pretty heavy on the memory, hopefully you have enough memory :)
